/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_cvface_jintest_JavaExcuteC */

#ifndef _Included_com_cvface_jintest_JavaExcuteC
#define _Included_com_cvface_jintest_JavaExcuteC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cvface_jintest_JavaExcuteC
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cvface_jintest_JavaExcuteC_display();

#ifdef __cplusplus
}
#endif
#endif

